import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

export const homeCollection = defineCollection({
  loader: glob({ pattern: './*.json', base: './src/content/home' }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    theMostCompleteBitcoinAPI: z.string(),
    bitcoinAPIBuiltFor: z.string(),
    developers: z.string(),
    accessComprehensiveBitcoinDataWithTheMostComfortableAPI: z.string(),
    startBuilding: z.string(),
    viewDocumentation: z.string(),
    uptime: z.string(),
    responseTime: z.string(),
    endpoints: z.string(),
    whyChooseBitcoinAPI: z.string(),
    convenientAPI: z.string(),
    detailedEndpointDocumentation: z.string(),
    wideVarietyOfData: z.string(),
    payOnlyForEndpointGroupsYouNeed: z.string(),
    mcpWithDocumentationForAI: z.string(),
    quickStart: z.string(),
    getBitcoinDataInSeconds: z.string(),
    curlExample: z.string(),
    apiEndpoints: z.string(),
    comprehensiveDataAcrossTheBitcoinEcosystem: z.string(),
    blocks: z.string(),
    latestBlocksBlockDetailsOrphanBlocks: z.string(),
    mempool: z.string(),
    unconfirmedTransactionsFees: z.string(),
    addresses: z.string(),
    balanceHistoryUtxos: z.string(),
    transactions: z.string(),
    decodeBroadcastFeeEstimates: z.string(),
    market: z.string(),
    priceVolumeOhlcvData: z.string(),
    readyToBuild: z.string(),
    startWithAFreeApiKey: z.string(),
    getYourApiKey: z.string(),
  }),
});
