/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns "ok" if the API is up and running.
         */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Returns information about the currently authenticated user.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /**
         * Delete user account
         * @description Permanently deletes user account. Requires no active subscriptions.
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset email
         * @description Sends a password reset link to the given email if the account exists.
         */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email and password
         * @description Authenticates a user and sets an HttpOnly access cookie.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out the current user
         * @description Clears the access cookie for the authenticated user.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset password using a reset token
         * @description Sets a new password for the user identified by the reset token from the email.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign up a new user
         * @description Registers a new user and sends a verification email.
         */
        post: operations["signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify email by token
         * @description Activates the user account associated with the verification token and sets the access cookie.
         */
        get: operations["verifyEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google OAuth callback
         * @description Handles the redirect from Google, exchanges the auth code, and sets the access cookie.
         */
        get: operations["googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start Google OAuth login flow
         * @description Redirects the user to the Google OAuth consent screen.
         */
        get: operations["googleLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Stripe Checkout session
         * @description Creates a Stripe Checkout session for subscribing to one or more rate-limit boosts.
         */
        post: operations["createBillingCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Stripe Customer Portal session
         * @description Creates a Stripe Customer Portal session for managing existing subscriptions.
         */
        post: operations["createBillingPortalSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/docs/ask-ai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask AI about Bitcoin API docs
         * @description Streams an AI-generated answer over Server-Sent Events. Events: `sources`, `token`, `done`. Client MUST send `Accept: text/event-stream`.
         */
        post: operations["askAiDocs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/api-keys/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List API keys
         * @description Returns all API keys belonging to the authenticated user.
         */
        get: operations["listApiKeys"];
        put?: never;
        /**
         * Create API key
         * @description Generates a new API key for the authenticated user.
         */
        post: operations["createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete API key
         * @description Permanently deletes an API key belonging to the authenticated user.
         */
        delete: operations["deleteApiKey"];
        options?: never;
        head?: never;
        /**
         * Update API key
         * @description Updates settings (like name, rate limits) for an existing API key.
         */
        patch: operations["updateApiKey"];
        trace?: never;
    };
    "/api/v1/me/api-keys/{id}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate API key
         * @description Replaces the API key with a new token; old token is invalidated.
         */
        post: operations["rotateApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/boosts/{operationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get boost details
         * @description Returns details for a specific rate-limit boost.
         */
        get: operations["getBoost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/boosts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active boosts
         * @description Returns rate-limit boosts owned by the authenticated user.
         */
        get: operations["listBoosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prices/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current price
         * @description Returns the latest price for a given trading pair from the configured exchange. For websocket use: wscat -c ws://localhost:8000/api/v1/prices/current?symbol=btcusdt
         */
        get: operations["getCurrentPrice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prices/klines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get historical and current klines (candles)
         * @description Returns historical klines (candles) and the current open kline (candle) for a given trading pair and interval. For websocket use: wscat -c ws://localhost:8000/api/v1/prices/klines?interval=1m
         */
        get: operations["getKlines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prices/klines/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current open kline (candle)
         * @description Returns the current open kline (candle) for a given trading pair and interval. For websocket use: wscat -c ws://localhost:8000/api/v1/prices/current?interval=1m
         */
        get: operations["getCurrentKline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        email: string;
                        createdAt: string;
                    };
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        email: string;
                    };
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: string;
                    };
                };
            };
        };
    };
    verifyEmail: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    googleCallback: {
        parameters: {
            query: {
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createBillingCheckoutSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    items: {
                        operationId: string;
                        /** @enum {integer} */
                        tier: 1 | 2 | 3;
                    }[];
                    returnUrl: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        url: string;
                    };
                };
            };
        };
    };
    createBillingPortalSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    returnUrl: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        url: string;
                    };
                };
            };
        };
    };
    askAiDocs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    query: string;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listApiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        apiKeys: {
                            id: string;
                            name: string;
                            token: string;
                            isActive: boolean;
                            perIpRateLimit?: number | null;
                            perIpWsConnectionsLimit?: number | null;
                            createdAt: string;
                        }[];
                    };
                };
            };
        };
    };
    createApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    perIpRateLimit?: number | null;
                    perIpWsConnectionsLimit?: number | null;
                };
            };
        };
        responses: {
            /** @description Default Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        token: string;
                        isActive: boolean;
                        perIpRateLimit?: number | null;
                        perIpWsConnectionsLimit?: number | null;
                        createdAt: string;
                    };
                };
            };
        };
    };
    deleteApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string | null;
                    perIpRateLimit?: number | null;
                    perIpWsConnectionsLimit?: number | null;
                };
            };
        };
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        token: string;
                        isActive: boolean;
                        perIpRateLimit?: number | null;
                        perIpWsConnectionsLimit?: number | null;
                        createdAt: string;
                    };
                };
            };
        };
    };
    rotateApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        token: string;
                        isActive: boolean;
                        perIpRateLimit?: number | null;
                        perIpWsConnectionsLimit?: number | null;
                        createdAt: string;
                    };
                };
            };
        };
    };
    getBoost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        operationId: string;
                        tier: number;
                        rateLimit: number;
                        wsConnectionsLimit?: number | null;
                        expiresAt?: string | null;
                        createdAt: string;
                        isActiveSubscription: boolean;
                    };
                };
            };
            /** @description Default Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                    };
                };
            };
        };
    };
    listBoosts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        boosts: {
                            id: string;
                            operationId: string;
                            tier: number;
                            rateLimit: number;
                            wsConnectionsLimit?: number | null;
                            expiresAt?: string | null;
                            createdAt: string;
                            isActiveSubscription: boolean;
                        }[];
                    };
                };
            };
        };
    };
    getCurrentPrice: {
        parameters: {
            query?: {
                symbol?: "btcusdt" | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Current price of the trading pair
                         * @example 50000.00
                         */
                        price: string;
                        /**
                         * @description ISO 8601 timestamp of the price recording
                         * @example 2024-01-01T00:00:00.000Z
                         */
                        time: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error code
                         * @example VALIDATION_ERROR
                         */
                        code: string;
                        /**
                         * @description Error message
                         * @example querystring/symbol must be equal to one of the allowed values
                         */
                        message: string;
                    };
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error code
                         * @example RATE_LIMIT_EXCEEDED
                         */
                        code: string;
                        /**
                         * @description Error message
                         * @example Rate limit exceeded, retry in 1 minute
                         */
                        message: string;
                    };
                };
            };
        };
    };
    getKlines: {
        parameters: {
            query: {
                symbol?: "btcusdt" | null;
                interval: "1m" | "5m" | "15m" | "30m" | "1h" | "4h" | "6h" | "12h" | "1d";
                limit?: number | null;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        klines: {
                            /**
                             * @description Opening time of the kline (candle) interval
                             * @example 2024-05-23T12:00:00.000Z
                             */
                            openTime: string;
                            /**
                             * @description Closing time of the kline (candle) interval
                             * @example 2024-05-23T12:01:00.000Z
                             */
                            closeTime: string;
                            /**
                             * @description Opening price
                             * @example 65000.00
                             */
                            open: string;
                            /**
                             * @description Highest price during the interval
                             * @example 65100.00
                             */
                            high: string;
                            /**
                             * @description Lowest price during the interval
                             * @example 64900.00
                             */
                            low: string;
                            /**
                             * @description Closing price
                             * @example 65050.00
                             */
                            close: string;
                            /**
                             * @description Trading volume during the interval
                             * @example 1.25
                             */
                            volume: string;
                            /**
                             * @description Number of trades
                             * @example 150
                             */
                            trades: number;
                            /**
                             * @description Whether the kline (candle) is fully closed
                             * @example true
                             */
                            isClosed: boolean;
                        }[];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error code
                         * @example VALIDATION_ERROR
                         */
                        code: string;
                        /**
                         * @description Error message
                         * @example querystring/symbol must be equal to one of the allowed values
                         */
                        message: string;
                    };
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error code
                         * @example RATE_LIMIT_EXCEEDED
                         */
                        code: string;
                        /**
                         * @description Error message
                         * @example Rate limit exceeded, retry in 1 minute
                         */
                        message: string;
                    };
                };
            };
        };
    };
    getCurrentKline: {
        parameters: {
            query: {
                symbol?: "btcusdt" | null;
                interval: "1m" | "5m" | "15m" | "30m" | "1h" | "4h" | "6h" | "12h" | "1d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Opening time of the kline (candle) interval
                         * @example 2024-05-23T12:00:00.000Z
                         */
                        openTime: string;
                        /**
                         * @description Closing time of the kline (candle) interval
                         * @example 2024-05-23T12:01:00.000Z
                         */
                        closeTime: string;
                        /**
                         * @description Opening price
                         * @example 65000.00
                         */
                        open: string;
                        /**
                         * @description Highest price during the interval
                         * @example 65100.00
                         */
                        high: string;
                        /**
                         * @description Lowest price during the interval
                         * @example 64900.00
                         */
                        low: string;
                        /**
                         * @description Closing price
                         * @example 65050.00
                         */
                        close: string;
                        /**
                         * @description Trading volume during the interval
                         * @example 1.25
                         */
                        volume: string;
                        /**
                         * @description Number of trades
                         * @example 150
                         */
                        trades: number;
                        /**
                         * @description Whether the kline (candle) is fully closed
                         * @example false
                         */
                        isClosed: boolean;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error code
                         * @example VALIDATION_ERROR
                         */
                        code: string;
                        /**
                         * @description Error message
                         * @example querystring/symbol must be equal to one of the allowed values
                         */
                        message: string;
                    };
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error code
                         * @example RATE_LIMIT_EXCEEDED
                         */
                        code: string;
                        /**
                         * @description Error message
                         * @example Rate limit exceeded, retry in 1 minute
                         */
                        message: string;
                    };
                };
            };
        };
    };
}
